<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>DnDFightTool.Domain.RollTemplate</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Infrastructure\Extensions\Extensions.csproj" />
		<ProjectReference Include="..\..\Infrastructure\Memory\Memory.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="CharacterSheet" />
		<InternalsVisibleTo Include="DnDEntitiesTests" />
	</ItemGroup>

</Project>
