<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DnDFightTool.UiTests.Scratch</RootNamespace>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageReference Include="NUnit" Version="4.5.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <ProjectReference Include="..\Framework\UiTestFramework.csproj" />
    <ProjectReference Include="..\TestableComponents\Components\TestableDndUi.Shared\TestableDndUi.Shared.csproj" />
    <ProjectReference Include="..\TestableComponents\UI\TestableCharacterSheetBlazorComponents\TestableCharacterSheetBlazorComponents.csproj" />
    <ProjectReference Include="..\TestableComponents\UI\TestableDnDQueryPrompter\TestableDnDQueryPrompter.csproj" />
    <ProjectReference Include="..\TestableComponents\UI\TestableFightBlazorComponents\TestableFightBlazorComponents.csproj" />
    <ProjectReference Include="..\..\tests\Domain\DomainTestsUtilities\DomainTestsUtilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Framework\AssemblyFixture.cs" Link="AssemblyFixture.cs" />
    <Compile Include="..\Framework\AssemblyInfo.cs" Link="AssemblyInfo.cs" />
  </ItemGroup>

</Project>
