<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>DnDFightTool.Components.DndUi.Web</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Blazored.FluentValidation" Version="2.2.0" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="MudBlazor" Version="9.4.0" />
        <PackageReference Include="UndoableMediator" Version="2.0.0-alpha1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DndUi.Shared\DndUi.Shared.csproj" />
        <ProjectReference Include="..\..\Infrastructure\AspNetCoreExtensions\AspNetCoreExtensions.csproj" />
        <ProjectReference Include="..\..\UI\CharacterSheetBlazorComponents\CharacterSheetBlazorComponents.csproj" />
        <ProjectReference Include="..\..\UI\DnDQueryPrompter\DnDQueryPrompter.csproj" />
        <ProjectReference Include="..\..\UI\FightBlazorComponents\FightBlazorComponents.csproj" />
    </ItemGroup>

</Project>
