<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>DnDFightTool.Business.DnDQueries</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MudBlazor" Version="9.4.0" />
		<PackageReference Include="UndoableMediator" Version="2.0.0-alpha2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Domain\CharacterSheet\CharacterSheet.csproj" />
		<ProjectReference Include="..\..\Domain\Fight\Fight.csproj" />
	</ItemGroup>

</Project>
