<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>DnDFightTool.Business.DnDUserInteraction</RootNamespace>

	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="UndoableMediator" Version="1.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Domain\DnDEntities\DnDEntities.csproj" />
	</ItemGroup>

</Project>

