<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MudBlazor" Version="8.11.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\UI\CharacterSheetBlazorComponents\CharacterSheetBlazorComponents.csproj" />
        <ProjectReference Include="..\..\UI\DnDQueryPrompter\DnDQueryPrompter.csproj" />
        <ProjectReference Include="..\..\UI\FightBlazorComponents\FightBlazorComponents.csproj" />
    </ItemGroup>

</Project>
